configure: use capital letters for variable names

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -105,12 +105,12 @@ CFLAGS_AUTO=
 CFLAGS_TRY=
 LDFLAGS_AUTO=
 LDFLAGS_TRY=
-srcdir=
-prefix=/usr/local
-exec_prefix='$(prefix)'
-bindir='$(exec_prefix)/bin'
-sharedir='$(prefix)/share'
-mandir='$(prefix)/share/man'
+SRCDIR=
+PREFIX=/usr/local
+EXEC_PREFIX='$(PREFIX)'
+BINDIR='$(EXEC_PREFIX)/bin'
+SHAREDIR='$(PREFIX)/share'
+MANDIR='$(PREFIX)/share/man'
 
 lua=auto
 selinux=auto
@@ -119,12 +119,12 @@ acl=auto
 for arg ; do
 case "$arg" in
 --help|-h) usage ;;
---srcdir=*) srcdir=${arg#*=} ;;
---prefix=*) prefix=${arg#*=} ;;
---exec-prefix=*) exec_prefix=${arg#*=} ;;
---bindir=*) bindir=${arg#*=} ;;
---sharedir=*) sharedir=${arg#*=} ;;
---mandir=*) mandir=${arg#*=} ;;
+--srcdir=*) SRCDIR=${arg#*=} ;;
+--prefix=*) PREFIX=${arg#*=} ;;
+--exec-prefix=*) EXEC_PREFIX=${arg#*=} ;;
+--bindir=*) BINDIR=${arg#*=} ;;
+--sharedir=*) SHAREDIR=${arg#*=} ;;
+--mandir=*) MANDIR=${arg#*=} ;;
 --enable-lua|--enable-lua=yes) lua=yes ;;
 --disable-lua|--enable-lua=no) lua=no ;;
 --enable-selinux|--enable-selinux=yes) selinux=yes ;;
@@ -142,21 +142,21 @@ LDFLAGS=*) LDFLAGS=${arg#*=} ;;
 esac
 done
 
-for i in srcdir prefix exec_prefix bindir ; do
+for i in SRCDIR PREFIX EXEC_PREFIX BINDIR SHAREDIR MANDIR ; do
 stripdir $i
 done
 
 #
 # Get the source dir for out-of-tree builds
 #
-if test -z "$srcdir" ; then
-srcdir="${0%/configure}"
-stripdir srcdir
+if test -z "$SRCDIR" ; then
+SRCDIR="${0%/configure}"
+stripdir SRCDIR
 fi
 abs_builddir="$(pwd)" || fail "$0: cannot determine working directory"
-abs_srcdir="$(cd $srcdir && pwd)" || fail "$0: invalid source directory $srcdir"
-test "$abs_srcdir" = "$abs_builddir" && srcdir=.
-test "$srcdir" != "." -a -f Makefile -a ! -h Makefile && fail "$0: Makefile already exists in the working directory"
+abs_srcdir="$(cd $SRCDIR && pwd)" || fail "$0: invalid source directory $SRCDIR"
+test "$abs_srcdir" = "$abs_builddir" && SRCDIR=.
+test "$SRCDIR" != "." -a -f Makefile -a ! -h Makefile && fail "$0: Makefile already exists in the working directory"
 
 #
 # Get a temp filename we can use
@@ -441,12 +441,12 @@ cat << EOF
 # This version of config.mk was generated by:
 # $cmdline
 # Any changes made here will be lost if configure is re-run
-srcdir = $srcdir
-prefix = $prefix
-exec_prefix = $exec_prefix
-bindir = $bindir
-MANPREFIX = $mandir
-SHAREPREFIX = $sharedir
+SRCDIR = $SRCDIR
+PREFIX = $PREFIX
+EXEC_PREFIX = $EXEC_PREFIX
+BINDIR = $BINDIR
+MANPREFIX = $MANDIR
+SHAREPREFIX = $SHAREDIR
 CC = $CC
 CFLAGS = $CFLAGS
 LDFLAGS = $LDFLAGS
@@ -470,6 +470,6 @@ LDFLAGS_SELINUX = $LDFLAGS_SELINUX
 EOF
 exec 1>&3 3>&-
 
-test "$srcdir" = "." || ln -sf $srcdir/Makefile .
+test "$SRCDIR" = "." || ln -sf $SRCDIR/Makefile .
 
 printf "done\n"
